In [1]:
## Importing Numpy
import numpy as np

In [2]:
# Loading text file by its name
data = np.loadtxt("textfilenp2.txt")
print(data)

print(type(data))

[[3.000e+00 6.000e+00 5.000e+00]
 [1.320e+02 2.310e+02 4.420e+02]
 [3.668e+03 4.559e+03 1.158e+03]
 [7.000e+00 8.100e+01 9.900e+01]]
<class 'numpy.ndarray'>


In [3]:
## Conversion from float to integer
data = np.loadtxt("textfilenp2.txt", dtype=int)
print(data)
print(type(data))
data.dtype

[[   3    6    5]
 [ 132  231  442]
 [3668 4559 1158]
 [   7   81   99]]
<class 'numpy.ndarray'>


dtype('int32')

In [4]:
## Skipping row
data = np.loadtxt("textfilenp2.txt",skiprows=1)
print(data)

[[ 132.  231.  442.]
 [3668. 4559. 1158.]
 [   7.   81.   99.]]


In [5]:
data = np.loadtxt("textfilenp2.txt",skiprows=3)
print(data)

[ 7. 81. 99.]


In [6]:
## For required rows
'''data = np.loadtxt("textfilenp2.txt", dtype=int, usecols=(1,4))
print(data)'''

'data = np.loadtxt("textfilenp2.txt", dtype=int, usecols=(1,4))\nprint(data)'

In [7]:
## Column into row
data = np.loadtxt("textfilenp2.txt", dtype=int,usecols=(1))
print(data)

[   6  231 4559   81]


In [8]:
## Integer into string
data = np.loadtxt("textfilenp2.txt", dtype=np.str0,usecols=(1))
print(data)

['6' '231' '4559' '81']
